language: python
python:
  - '3.6.5'

services:
  - postgresql

addons:
  firefox: latest

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.20.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

before_script:
  - pip install -r requirement.txt
  - psql -c 'create database travis_ci_test;' -U postgres

env: DJANGO_SETTINGS_MODULE="settings.travis"
  - MOZ_HEADLESS=1

script:
  - python youarenotalone/manage.py test

branches:
  only:
    - master