# Generated by Django 2.0.7 on 2018-07-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='coordinate_lat',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='coordinate_lng',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
