# Generated by Django 2.0.7 on 2018-09-08 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20180903_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(max_length=45)),
                ('postalCode', models.IntegerField()),
                ('coordinateLng', models.DecimalField(decimal_places=10, max_digits=12)),
                ('coordinateLat', models.DecimalField(decimal_places=10, max_digits=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='coordinateLat',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='coordinateLng',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='website.City'),
        ),
    ]
