# Generated by Django 2.0.7 on 2018-09-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='interestName',
            field=models.CharField(max_length=35),
        ),
    ]
