# Generated by Django 2.0.7 on 2018-09-16 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20180916_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='website.City'),
            preserve_default=False,
        ),
    ]
